### ISSUE TITLE
Alive?

### ISSUE THREAD

**Issue by trans** [joxa/joxa#82]
Is Joxa still being developed, or is it basically a dead project? If so, what is the reason it was abandoned?

**Comment by hhkbp2** [comment]
It has been dormant for awhile. I think there are many other things which keep @ericbmerritt busy so that he could not put a hand on this project for now.

**Comment by ericbmerritt** [comment]
@trans @hhkbp2 has the right of it. I just don't have much time to dedicate to it anymore.

**Comment by trans** [comment]
Totally understand time the time thing. It's too bad though. I was looking through the code and it looks like a really nice project. Perhaps if you could find a bit of time to explain the internals in detail others could pick up development?

**Comment by hhkbp2** [comment]
@trans About the internals, maybe you could take a look at https://vimeo.com/49116180

**Comment by trans** [comment]
@hhkbp2 Thanks. That helped a some, definitely. But it would be helpful too if the whole build process was explained.

**Comment by hhkbp2** [comment]
@trans 
Joxa is written to be self-bootstrapped. So the whole building process is about three types of transform:

1. The ast files is compiled by Eralng compiler to the Joxa compiler beam files
1. Escriptize the Joxa compiler beam files into a standardlone bin
1. The Joxa compiler compiles Joxa source files to ast or beam files

It's not easy to understand the whole picture since it is complex indeed. You could refer to this Makefile

https://github.com/hhkbp2/joxa/blob/clearer_build/Makefile

and take a look at the the make targets specially. It tries to make the building process clearer.

**Comment by trans** [comment]
Are the AST files hand coded? That must have been a hell of a lot of work!

Yeah, the makefile process is a challenge to follow (for me at least). I'll keep at it. Thanks.

**Comment by trans** [comment]
On second thought that can't be right. You've bootstrapped it... Joxa compiles Joxa into those ast files?

**Comment by ericbmerritt** [comment]
Guys, sorry about my slow response. I have been traveling the last few days. 

@trans on the ast. They are not hand coded. Joxa does compile joxa into those ast files. Then we compile them as part of the bootstrapping process. Its actually annoyingly complex at the moment. I have thought for a long time that I shouldn't have bootstrapped the language. Ie, we should have left the core language in Erlang and ran Joxa on top of it.  It would have made contributing to and supporting the language much easier. 

One of the paths I think about going forward is to reset the repo to pre-bootstrap days and start fresh from there. I think it would revive the language a bit.

**Comment by trans** [comment]
OTOH, Joxa in Joxa is *pretty damn cool*. But I hear you.
